### ISSUE TITLE
Update BibliographicItem model (and migrate from StandardDocument)

### ISSUE THREAD

**Issue by ronaldtse** [riboseinc/isodoc-models#15]
Moved from StandardDocument to BibItem:

* CopyrightAssociation moved to BibItem
* DocumentStatus
* DocumentType
* DocumentIdentifier
* TitleInfo
* Author

BibItem refactored:
* Person / Organization inherit from Contributor
* Publisher information described in ContributorRole
* Added LocalizedString definition to allow for multiple languages in title (from StandardDocument)
* ParagraphBlocks changed to FormattedString which allows rich text

**Comment by opoudjis** [comment]
Ticket encompasses all updates to Isodoc models up to 2017-02-07.

**Comment by opoudjis** [comment]
So far: updated grammars for top element and all biblio. Done proper inheritance.

**Comment by opoudjis** [comment]
All grammars updated. Keeping ticket open for feedback discussion with @ronaldtse

**Comment by opoudjis** [comment]
Feedback. I'll do this here against my better judgement; I'm numbering each item separately for discussion—please cite item number for each response.

* Item 15-1: per #21, both `term/origin` and `docrelation/reference` should be `eref`, not `citation`. Citation should be limited to the bibliography model, for conceptual reasons: any reference to a bibitem in the text item should be an eref. 
* Item 15-2: change `FormattedString@type` to `FormattedString@format`. I am realising FormattedString as a mixin with existing elements, and those elements already all use `@type`
* Item 15-3: Currently `FormattedString@format` is mandatory; it would be polite to make it optional with a default value of `plain`.
* Item 15-4: `affiliation/name` is optional. You didn't name my affiliation with Ribose in the RFC draft, for example.
* Item 15-5: `BibliographicItem` has an `@id`, because that's how citations work. This is an artefact of including bibliography in a document model, so you may choose to leave it out still. (The `bibdata` instance would not have an `@id`.)
* Item 15-6: `BibliographicItem/title` is optional: it is mutually exclusive with `formattedref`.
* Item 15-7: `BibliographicItem/copyright` is optional (though it is mandatory in `bibdata`)
* Item 15-8: `docidentifier` should have a `@type`.
* Item 15-9: I don't the point of `version/version`, and IsoStandard needs `version/draft`. Rename `version/version` to `version/draft`?
* Item 15-10: I'd prefer to rename `bibdata/workgroup` as `bibdata/committee`; the tech committee is in fact the only mandatory element of the container.

**Comment by ronaldtse** [comment]
* Item 15-1: Updated in #21
* Item 15-2: Done. Thinking further isn't it better to use an URI for format, since there could be isodoc, csd, etc and many other formats? Better to be extensible.
* Item 15-3: Done with 15-2.
* Item 15-4: Agree. Done.
* Item 15-5: it sounds like we should better separate the Bib model from the Doc model? I'm not sure what exactly should be done here.
* Item 15-6: I feel that this is slightly wrong. A bibliographic item should always have a title? I think we're having issues with this because we're mixing "BibItem" and "BibData". I don't think we have a "BibData" now. Perhaps we should separate "BibData" (the data) from "BibItem" (the entry of BibData included in a Document) and "BibCitation" (how to refer to a BibItem from the Document)?
* Item 15-7: as above.
* Item 15-8: Added "DocumentIdentifier" class that takes "id" and "type" Strings. Not sure if this is sufficient?
* Item 15-9: for `version` I meant a version string like "10.2.3", and for `draft` I meant the sequential draft number that represents the stages for sub/pre-`version`s, e.g., "10.2.3" revision 5 then becomes "10.2.4". Any suggestions on making this better?
* Item 15-10: The reason I put `workgroup` as the unit is that most projects have a workgroup, but according to Directives Part 1, a work group is optional. However when there *is* a workgroup we want them to provide better granularity rather than just say the committee. Thoughts?
* Item 15-11: You're right. Should we do URI?

**Comment by opoudjis** [comment]
15-3, 15-4, 15-8: Resolved

15-1, 15-5, 15-6, 15-7: The solution to these is:

* To have biblio:bibItem inherited into doc:bibitem, with added attribute, `@id`
* To have bib:citation inherited into doc:eref, adding attribute `@citeAs`. (As I say in #21, bib:citation can stay where it is: I'm treating bib:citation as an abstract type, and doc:eref as its instantiation in a document.)
* To have biblio:bibItem separately inherited into doc:bibdata, without adding `@id`, but making `title` and `copyright` mandatory.

... What do you think?

15-2, 15-11: The more natural way of dealing with formats is MIME types. (I don't even know what the URL of a format type would be.) I agree they should be extensible. So: text/plain, text/html, application/docbook+xml [which they never got around to registering], application/tei+xml, text/X-asciidoc, text/markdown, application/X-isodoc+xml

15-9: This is bumping into notions of major and minor releases, but I can see that there is a distinction between versions, which are published, and drafts, which are not. There's also a problem that version now is hard to differentiate from edition, though.  (And version now seems to be missing from the model.) I think edition should be subsumed into version, and draft can stay separate; I will need to explain it in the Readme though.

15-10: The container includes both committee and workgroup, and should be named more inclusively; editorialsubgroup? editorialgroup? suborganisation? isoeditorial?

**Comment by opoudjis** [comment]
15-12: quote/author is logically redundant to quote/source, which has a citation incorporates both the author and the work title. The separation of author and source is an artefact of a particular convention of citation. In fact, using an idiosyncratic citation convention just for quotations seems to me to be a bad idea. Quote/author should be removed.

**Comment by ronaldtse** [comment]
15-1, 15-5, 15-6, 15-7: agree with your approach, could you make the changes?

15-2, 15-11: totally forgot about MIME types. However this raises a question: Can then IsoDoc contain fragments of IsoDoc within? If it is allowed, what happens to the document attributes provided in the internal IsoDoc? Can attributes that are defined outside be used by the  internal IsoDoc?

15-9: perhaps we should start a new issue for versioning and settle it once and for all?

15-10: or editorialgroup? maybe projectgroup?

**Comment by opoudjis** [comment]
15-9: now refer #22

**Comment by opoudjis** [comment]
15-12 now resolved.

**Comment by opoudjis** [comment]
15-1, 15-5, 15-6, 15-7: updated grammar and diagrams

**Comment by opoudjis** [comment]
15-10: projectgroup

**Comment by opoudjis** [comment]
15-2, 15-11: Yes, Isodoc can contain Isodoc fragments in its bibliography; in fact, right now it already does, as that is how the bibliographies in the Rice Model are being rendered. 

I am ignoring the document attributes in formattedstrings in *validation*, because of how RNC is broken in its handling of wildcard attributes; that means I am ignoring IDREF checks for formatted strings containing Isodoc. But any anchors pointing to them from outside the formatted string will work just fine in the current gem, because I simply haven't told it not to—and I don't see a good reason not to.
