### ISSUE TITLE
Extend localities?

### ISSUE THREAD

**Issue by opoudjis** [riboseinc/isodoc-models#23]
Because of the nature of ISO documents, external references can be to tables, figures, notes, annexes, etc; e.g. the rice document cites 

````
NOTE: This table is based on <<ISO7301>>, Table 1.

....

Calculate the crude protein content of the dry product by multiplying the value of the nitrogen content by the conversion factor specified in <<ISO20483>>, Annex C and Table C.1
````

Should we extend localities to include such localities? We do need to define the possible localities currently, since they are detected by string matching on the citation string.

**Comment by ronaldtse** [comment]
Agree with extending citation localities -- it's just that since it is not an object we refer to but an unvalidated locality, we can't be sure it is correct and therefore the types/terms we use to refer it may not entirely be correct.

When citing an ISO Standard, we are sure it contains a determined set (and combinations) of locality types. But when it is of a different document type, we just have to accept free-form text?

**Comment by opoudjis** [comment]
Ultimately, we will have to. But I will have to work out a microformats for permitting this inside an asciidoc attribute. Maybe `locality:table`, with the locality prefix namespacing an unknown locality:

`<<iso678,locality:frontispiece 5,page 9>>`

**Comment by opoudjis** [comment]
I will (later) allow free text, with this "locality:X" microformat.

**Comment by opoudjis** [comment]
the only catch is i18n

but we can add them to user-specified i18n template

if you use these and expect them to render in different languages, you have to provide the i18n translation

**Comment by opoudjis** [comment]
and issue warning if a free type occurs in a citation to a well-known document type, or for that matter an extraneous one, such as section as opposed to clause in an ISO document

**Comment by opoudjis** [comment]
Not doing warnings: these are deliberate actions from the user.

Implemented, rspec'd and documented.
