### ISSUE TITLE
Separate IsoBibliographicItem and StandardBibliographicItem?

### ISSUE THREAD

**Issue by ronaldtse** [riboseinc/isodoc-models#27]
@opoudjis Is this necessary?

Given that we separate IsoStandardDocument and CSD, we might want to separate IsoBibliographicItem into CSDBibliographicItem (which inherits from StandardBibliographicItem)...

**Comment by opoudjis** [comment]
ISO standards need to know the more detailed information about ISO standards: the distinctions between title parts, for example, since they are validated. That is particularly important for bibdata. Similarly, CSD will need to know particulars specific to CSD. Does ISO need to know about CSD though? 

I think there can be local inheritance and elaboration of standards types. I'm not convinced they need to become split classes that are both present in a standard.
